### PR TITLE
fix: Step case overwriting prevention by hypothetical ID

### LINKED ISSUE #392: [Bug] Step templated case may overwrite another step text area
https://github.com/user-attachments/assets/302477d3-2a62-4973-94ac-865009494f55

In this example:
1. created a step templated case
2. create step 1
3. add step 2 times via top button (created step 1 and step 2, the old step 1 became step 3)
4. add value to step 2
5. add value to step 1

result:
1. value of step 2 is changed to be same like step 1
2. Index (left number) become 1

### PR DESCRIPTION
**Pull request by tokidoki11**
Closes: https://github.com/kimatata/unittcms/issues/392

## Context
We have found a bug when having a step based test, step may overwrite each other

## Problem
The reason of overwriting and overlapping is because `plusCount` may have the same value with ID
since plusCount is always starts at 0, it may clash with value already stored in database (step with id 1)

## Description

1. Create an idCounter, to keep track of ID. 
2. on first load (useEffect), the idCounter will be set the Max value of id in the TestCase
3. on add step, it will increment

note:

I changed update and delete code as well, it is not required, please tell me if you want to revert.
I feel that is cleaner code

### CODE REVIEW

File: frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseStepsEditor.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default function StepsEditor({ isDisabled, steps, onStepUpdate, onStepPlu
       {filteredSteps.map((step, index) => (
         <div key={index} className="flex items-center my-1">
           <Avatar className="me-2" size="sm" name={step.caseSteps.stepNo.toString()} />
-          <div key={step.id} className="grow flex gap-2">
+          <div key={step.uid} className="grow flex gap-2">
```
Comment (tokidoki11) [inline frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseStepsEditor.tsx]: changed by accident, may not be required
whats the purpose of uid anyway

File: frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseEditor.tsx [hunk 2]
```diff
@@ -201,18 +205,17 @@ export default function CaseEditor({
...
-          } else {
-            return step;
-          }
-        }),
-      });
+    if (!testCase.Steps) {
+      return;
     }
+
+    const stepIndex = testCase.Steps.findIndex((step) => step.id === stepId);
```
Comment (kimatata) [inline frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseEditor.tsx]: The old code used map to return a new array, but now you're directly mutating testCase.Steps[stepIndex]. React state should be treated as immutable — see the https://react.dev/learn/updating-objects-in-state. 

Please revert to the map-based approach🙏

File: frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseStepsEditor.tsx (hunk 1 above)
Comment (kimatata) [reply frontend/src/app/[locale]/projects/[projectId]/folders/[folderId]/cases/[caseId]/CaseStepsEditor.tsx]: Honestly, I can't remember exactly why I added uid 😅 But looking at the timing it was introduced and the fact that it's a frontend-only field (like editState), I think it was meant to identify multiple unsaved new steps that don't have a real DB ID yet.

That said, uid is only properly set in onPlusClick for newly added steps — existing steps loaded from DB don't have it, so step.uid will be undefined for them. Changing key={step.id} to key={step.uid} could cause some unexpected issues because of that.

Could you revert this change?

**Comment by tokidoki11** [comment]
@kimatata hi, i fix the reviewed item

could you pls recheck? thanks a lot

**Review by kimatata — APPROVED** [review]

**Comment by kimatata** [comment]
Merged, thanks!
